trigger:
  branches:
    include:
      - Usecase7

pool:
  vmImage: 'ubuntu-latest'

variables:
  # Variables for your deployment
  azureSubscription: 'ARM'
  resourceGroupName: 'North Europe'
  deploymentName: 'my-deployment'
  templateFile: 'azuredeploy.json'
  location: 'North Europe'  # You can adjust this to match your ARM template parameters

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: $(azureSubscription)
    scriptType: 'bash'
    scriptPath: '$(Build.SourcesDirectory)/deploy.sh'
    arguments: '-g $(resourceGroupName) -n $(deploymentName) -f $(Build.SourcesDirectory)/$(templateFile) -l $(location)'
  displayName: 'Deploy ARM Template'
